version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build -t openmaraude/geofaker:${CIRCLE_TAG} .
            docker tag openmaraude/geofaker:${CIRCLE_TAG} openmaraude/geofaker:latest
      - run:
          name: Publish docker Image to hub.docker.com
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push openmaraude/geofaker:${CIRCLE_TAG}
            docker push openmaraude/geofaker:latest

workflows:
  # Build artifacts, ignore all branches, only run for all tags.
  artifacts:
    jobs:
      - build:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
